### ISSUE TITLE
Upstream this into kedplasma-addons

### ISSUE THREAD

**Issue by Pointedstick** [zzag/dynamic-wallpaper#9]
This thins is so cool. IMO it should be upstreamed and live in kdeplasma-addons, so it gets shipped by default!

**Comment by zzag** [comment]
In general I'm not against that, but I also see nothing wrong with having "third party" status.

You need to be aware of several minor issues:
* position of the Sun is used to get the current wallpaper, which means it's not possible to specify duration of each individual image, see #7 for more details;
* there are only a few wallpapers for this plugin in the wild;
* this plugin doesn't follow the Frameworks coding style.

**Comment by Pointedstick** [comment]
> In general I'm not against that, but I also see nothing wrong with having "third party" status.

Me neither, but the advantage would be that once it's integrated, it gets more eyeballs, more development, and more wallpapers that are compatible with it. Also the code becomes immortal, and not tied to a specific person anymore.

**Comment by zzag** [comment]
Sorry for the late response.

As I said previously I'm not against upstreaming. The biggest problem with this dynamic wallpaper plugin is weak ecosystem around it. For the most part this is my fault because I didn't put a lot of effort into it. I made this plugin mainly to challenge myself - underlying math problems are very fun!

Looking at dynamic wallpapers made by Apple leaves impression that a lot of effort was put into taking gorgeous shots of Mojave desert or Santa Catalina island. If no one from community can make similar wallpapers, there's absolutely no point for proceeding any further as nobody will use this plugin.

**Comment by zzag** [comment]
Using KPackage will be a prerequisite for upstreaming.

**Comment by Schlaefer** [comment]
> If no one from community can make similar wallpapers, there's absolutely no point for proceeding any further as nobody will use this plugin.

Just a heads up that other communities are generating more content already:

- https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Community-created-themes
- https://dynamicwallpaper.club/

**Comment by zzag** [comment]
> * https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Community-created-themes

These wallpapers are not suitable because they don't come with the Sun metadata provided.

> * https://dynamicwallpaper.club/

The problem with these wallpapers is that they are shipped as .heic files. See #6

**Comment by Schlaefer** [comment]
> These wallpapers are not suitable because they don't come with the Sun metadata provided.
 
> The problem with these wallpapers is that they are shipped as .heic files. See #6

There are no drop-in solution, but you can easily make them work for yourself. The point was: the biggest hurdle is finding quality source material, and these are good.

**Comment by zzag** [comment]
Well, there are actually two issues. The first one as you mentioned already is finding good content. The other one is sharing wallpapers.

**Comment by zzag** [comment]
I've spent some time for adding support for "timed" dynamic wallpapers. So, this plugin supports two types of dynamic wallpapers at the moment - solar and timed.

## Solar

A solar dynamic wallpaper provides the Sun's position along each image, e.g.

```json
{
  "name": "Fancy wallpaper",
  "type": "solar",
  "images": [
    {
      "elevation": 0,
      "azimuth": 0,
      "filename": "foobar.png"
    }
  ]
}
```

## Timed

A timed dynamic wallpaper provides a real number between 0 and 1 along each image. That number specifies how far the day has advanced. 0 and 1 correspond to midnight, and 0.5 corresponds to noon.

```json
{
  "name": "Fancy wallpaper",
  "type": "timed",
  "images": [
    {
      "time": 0,
      "filename": "foo.png"
    },
    {
      "time": 0.5,
      "filename": "bar.png"
    },
    {
      "time": 0.7,
      "filename": "baz.png"
    }
  ]
}
```

Timed wallpapers are easier to create because you don't have to hassle with the Sun's position metadata.

---

I've also written a tool that can be used to convert a .heic dynamic wallpaper to a format suitable for this wallpaper plugin, however it is not public yet.

**Comment by zzag** [comment]
> Using KPackage will be a prerequisite for upstreaming.

Done.

One can now run kpackagetool5 to install a dynamic wallpaper, e.g.

```
kpackagetool5 --type Wallpaper/Dynamic --install <package directory>
```

**Comment by zzag** [comment]
So, I've tried to upstream some bits of the plugin, however that didn't succeed. Given that and my previous failed attempts to clean up some code in kwin, which exhausted me mentally, I won't upstream this plugin and it will remain as my side project.

Thank you for showing interest in this wallpaper plugin and suggesting to upstream it.

**Comment by Pointedstick** [comment]
All right. fair enough. It is really nice!
